const students = [
  {
    id: "232031001",
    name: "Rakib Hasan",
    batch: "31st",
    program: "BSc in CSE",
    department: "Computer Science & Engineering",
    university: "Feni University",
    semester: "6th",
    email: "rakib231031001@feniuniversity.ac.bd",
    cgpa: 3.99,
  },
  {
    id: "232031002",
    name: "Shakil Ahmed",
    batch: "31st",
    program: "BSc in CSE",
    department: "Computer Science & Engineering",
    university: "Feni University",
    semester: "6th",
    email: "shakil231031002@feniuniversity.ac.bd",
    cgpa: 3.99,
  },
  {
    id: "232031003",
    name: "Tanjim Rahman",
    batch: "31st",
    program: "BSc in CSE",
    department: "Computer Science & Engineering",
    university: "Feni University",
    semester: "6th",
    email: "tanjim231031003@feniuniversity.ac.bd",
    cgpa: 3.99,
  },
  {
    id: "232031004",
    name: "Mehedi Hasan",
    batch: "31st",
    program: "BSc in CSE",
    department: "Computer Science & Engineering",
    university: "Feni University",
    semester: "6th",
    email: "mehedi231031004@feniuniversity.ac.bd",
    cgpa: 3.99,
  },
  {
    id: "232031005",
    name: "Imran Hossain",
    batch: "31st",
    program: "BSc in CSE",
    department: "Computer Science & Engineering",
    university: "Feni University",
    semester: "6th",
    email: "imran231031005@feniuniversity.ac.bd",
    cgpa: 3.99,
  },
];

module.exports = students;